### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by whit1206** [titosemi/jira-api#3]
Hello,
Thanks for the great example. I would like to run this on a server, but what is the license that you require? Thanks,
Chris

**Comment by titosemi** [comment]
Hi @whit1206,

I would use the MIT license.
The problem here is that I originally forked the project and made some modifications.
There is an open issue on the original fork regarding the license #8 but the original author haven't been active for a while :disappointed: 

I also tried to contribute back my changes https://github.com/FayP/JIRA-php/pull/5
